version: "3.8"
services:
  # backend:
  #   image: state-search-be:latest
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   depends_on:
  #     - pg
  #     - qdrant
  #   ports:
  #     - ${BACKEND_PORT}:7720
  #   volumes:
  #     - ${MODEL_NAME_OR_PATH}:/code/model:z

  # frontend:
  #   image: lean-state-search:latest
  #   depends_on:
  #     - pg
  #     - backend
  #   ports:
  #     - ${FRONTEND_PORT}:3000
  pg:
    container_name: state-search-db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=statesearch
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
  qdrant:
    container_name: state-search-vb
    image: qdrant/qdrant
    depends_on:
      - pg
    environment:
      - QDRANT__SERVICE__HTTP_HOST=0.0.0.0
    ports:
      - ${QDRANT_PORT}:6333
    volumes:
      - ${QDRANT_VOLUME}:/qdrant/storage:z
