# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state_search/v1/state_search.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'state_search/v1/state_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"state_search/v1/state_search.proto\x12\x0fstate_search.v1\"\x8c\x01\n\x07Theorem\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n\x04\x63ode\x18\x03 \x01(\tR\x04\x63ode\x12\x10\n\x03rev\x18\x04 \x01(\tR\x03rev\x12\x16\n\x06module\x18\x05 \x01(\tR\x06module\x12\x1f\n\x0b\x66ormal_type\x18\x06 \x01(\tR\nformalType\"\x12\n\x10GetAllRevRequest\"\'\n\x11GetAllRevResponse\x12\x12\n\x04revs\x18\x01 \x03(\tR\x04revs\"X\n\x14SearchTheoremRequest\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\x12\x18\n\x07nresult\x18\x02 \x01(\x05R\x07nresult\x12\x10\n\x03rev\x18\x03 \x01(\tR\x03rev\"K\n\x15SearchTheoremResponse\x12\x32\n\x07results\x18\x01 \x03(\x0b\x32\x18.state_search.v1.TheoremR\x07results\"z\n\x0f\x46\x65\x65\x64\x62\x61\x63kRequest\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n\ntheorem_id\x18\x02 \x01(\tR\ttheoremId\x12\x1a\n\x08relevant\x18\x03 \x01(\x08R\x08relevant\x12\x16\n\x06update\x18\x04 \x01(\x08R\x06update\"\x12\n\x10\x46\x65\x65\x64\x62\x61\x63kResponse2\x9d\x02\n\x16LeanStateSearchService\x12R\n\tGetAllRev\x12!.state_search.v1.GetAllRevRequest\x1a\".state_search.v1.GetAllRevResponse\x12^\n\rSearchTheorem\x12%.state_search.v1.SearchTheoremRequest\x1a&.state_search.v1.SearchTheoremResponse\x12O\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12 .state_search.v1.FeedbackRequest\x1a!.state_search.v1.FeedbackResponseB\x80\x01\n\x13\x63om.state_search.v1B\x10StateSearchProtoP\x01\xa2\x02\x03SXX\xaa\x02\x0eStateSearch.V1\xca\x02\x0eStateSearch\\V1\xe2\x02\x1aStateSearch\\V1\\GPBMetadata\xea\x02\x0fStateSearch::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_search.v1.state_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.state_search.v1B\020StateSearchProtoP\001\242\002\003SXX\252\002\016StateSearch.V1\312\002\016StateSearch\\V1\342\002\032StateSearch\\V1\\GPBMetadata\352\002\017StateSearch::V1'
  _globals['_THEOREM']._serialized_start=56
  _globals['_THEOREM']._serialized_end=196
  _globals['_GETALLREVREQUEST']._serialized_start=198
  _globals['_GETALLREVREQUEST']._serialized_end=216
  _globals['_GETALLREVRESPONSE']._serialized_start=218
  _globals['_GETALLREVRESPONSE']._serialized_end=257
  _globals['_SEARCHTHEOREMREQUEST']._serialized_start=259
  _globals['_SEARCHTHEOREMREQUEST']._serialized_end=347
  _globals['_SEARCHTHEOREMRESPONSE']._serialized_start=349
  _globals['_SEARCHTHEOREMRESPONSE']._serialized_end=424
  _globals['_FEEDBACKREQUEST']._serialized_start=426
  _globals['_FEEDBACKREQUEST']._serialized_end=548
  _globals['_FEEDBACKRESPONSE']._serialized_start=550
  _globals['_FEEDBACKRESPONSE']._serialized_end=568
  _globals['_LEANSTATESEARCHSERVICE']._serialized_start=571
  _globals['_LEANSTATESEARCHSERVICE']._serialized_end=856
# @@protoc_insertion_point(module_scope)
