# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from state_search.v1 import state_search_pb2 as state__search_dot_v1_dot_state__search__pb2


class LeanStateSearchServiceStub(object):
    """Service for searching.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllRev = channel.unary_unary(
                '/state_search.v1.LeanStateSearchService/GetAllRev',
                request_serializer=state__search_dot_v1_dot_state__search__pb2.GetAllRevRequest.SerializeToString,
                response_deserializer=state__search_dot_v1_dot_state__search__pb2.GetAllRevResponse.FromString,
                _registered_method=True)
        self.SearchTheorem = channel.unary_unary(
                '/state_search.v1.LeanStateSearchService/SearchTheorem',
                request_serializer=state__search_dot_v1_dot_state__search__pb2.SearchTheoremRequest.SerializeToString,
                response_deserializer=state__search_dot_v1_dot_state__search__pb2.SearchTheoremResponse.FromString,
                _registered_method=True)
        self.Feedback = channel.unary_unary(
                '/state_search.v1.LeanStateSearchService/Feedback',
                request_serializer=state__search_dot_v1_dot_state__search__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=state__search_dot_v1_dot_state__search__pb2.FeedbackResponse.FromString,
                _registered_method=True)
        self.Click = channel.unary_unary(
                '/state_search.v1.LeanStateSearchService/Click',
                request_serializer=state__search_dot_v1_dot_state__search__pb2.ClickRequest.SerializeToString,
                response_deserializer=state__search_dot_v1_dot_state__search__pb2.ClickResponse.FromString,
                _registered_method=True)
        self.Call = channel.unary_unary(
                '/state_search.v1.LeanStateSearchService/Call',
                request_serializer=state__search_dot_v1_dot_state__search__pb2.CallRequest.SerializeToString,
                response_deserializer=state__search_dot_v1_dot_state__search__pb2.CallResponse.FromString,
                _registered_method=True)


class LeanStateSearchServiceServicer(object):
    """Service for searching.
    """

    def GetAllRev(self, request, context):
        """Get all existing revs in database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTheorem(self, request, context):
        """Search theorem according to the query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Feedback(self, request, context):
        """Collect feedbacks from user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Click(self, request, context):
        """Collect click events from user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeanStateSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllRev': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllRev,
                    request_deserializer=state__search_dot_v1_dot_state__search__pb2.GetAllRevRequest.FromString,
                    response_serializer=state__search_dot_v1_dot_state__search__pb2.GetAllRevResponse.SerializeToString,
            ),
            'SearchTheorem': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTheorem,
                    request_deserializer=state__search_dot_v1_dot_state__search__pb2.SearchTheoremRequest.FromString,
                    response_serializer=state__search_dot_v1_dot_state__search__pb2.SearchTheoremResponse.SerializeToString,
            ),
            'Feedback': grpc.unary_unary_rpc_method_handler(
                    servicer.Feedback,
                    request_deserializer=state__search_dot_v1_dot_state__search__pb2.FeedbackRequest.FromString,
                    response_serializer=state__search_dot_v1_dot_state__search__pb2.FeedbackResponse.SerializeToString,
            ),
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=state__search_dot_v1_dot_state__search__pb2.ClickRequest.FromString,
                    response_serializer=state__search_dot_v1_dot_state__search__pb2.ClickResponse.SerializeToString,
            ),
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=state__search_dot_v1_dot_state__search__pb2.CallRequest.FromString,
                    response_serializer=state__search_dot_v1_dot_state__search__pb2.CallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'state_search.v1.LeanStateSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('state_search.v1.LeanStateSearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeanStateSearchService(object):
    """Service for searching.
    """

    @staticmethod
    def GetAllRev(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/state_search.v1.LeanStateSearchService/GetAllRev',
            state__search_dot_v1_dot_state__search__pb2.GetAllRevRequest.SerializeToString,
            state__search_dot_v1_dot_state__search__pb2.GetAllRevResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTheorem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/state_search.v1.LeanStateSearchService/SearchTheorem',
            state__search_dot_v1_dot_state__search__pb2.SearchTheoremRequest.SerializeToString,
            state__search_dot_v1_dot_state__search__pb2.SearchTheoremResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Feedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/state_search.v1.LeanStateSearchService/Feedback',
            state__search_dot_v1_dot_state__search__pb2.FeedbackRequest.SerializeToString,
            state__search_dot_v1_dot_state__search__pb2.FeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/state_search.v1.LeanStateSearchService/Click',
            state__search_dot_v1_dot_state__search__pb2.ClickRequest.SerializeToString,
            state__search_dot_v1_dot_state__search__pb2.ClickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/state_search.v1.LeanStateSearchService/Call',
            state__search_dot_v1_dot_state__search__pb2.CallRequest.SerializeToString,
            state__search_dot_v1_dot_state__search__pb2.CallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LeanGraphServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDependencyNodesAndEdges = channel.unary_unary(
                '/state_search.v1.LeanGraphService/GetDependencyNodesAndEdges',
                request_serializer=state__search_dot_v1_dot_state__search__pb2.GetDependencyNodesAndEdgesRequest.SerializeToString,
                response_deserializer=state__search_dot_v1_dot_state__search__pb2.GetDependencyNodesAndEdgesResponse.FromString,
                _registered_method=True)
        self.GetDependentNodesAndEdges = channel.unary_unary(
                '/state_search.v1.LeanGraphService/GetDependentNodesAndEdges',
                request_serializer=state__search_dot_v1_dot_state__search__pb2.GetDependentNodesAndEdgesRequest.SerializeToString,
                response_deserializer=state__search_dot_v1_dot_state__search__pb2.GetDependentNodesAndEdgesResponse.FromString,
                _registered_method=True)


class LeanGraphServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDependencyNodesAndEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDependentNodesAndEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeanGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDependencyNodesAndEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDependencyNodesAndEdges,
                    request_deserializer=state__search_dot_v1_dot_state__search__pb2.GetDependencyNodesAndEdgesRequest.FromString,
                    response_serializer=state__search_dot_v1_dot_state__search__pb2.GetDependencyNodesAndEdgesResponse.SerializeToString,
            ),
            'GetDependentNodesAndEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDependentNodesAndEdges,
                    request_deserializer=state__search_dot_v1_dot_state__search__pb2.GetDependentNodesAndEdgesRequest.FromString,
                    response_serializer=state__search_dot_v1_dot_state__search__pb2.GetDependentNodesAndEdgesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'state_search.v1.LeanGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('state_search.v1.LeanGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeanGraphService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDependencyNodesAndEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/state_search.v1.LeanGraphService/GetDependencyNodesAndEdges',
            state__search_dot_v1_dot_state__search__pb2.GetDependencyNodesAndEdgesRequest.SerializeToString,
            state__search_dot_v1_dot_state__search__pb2.GetDependencyNodesAndEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDependentNodesAndEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/state_search.v1.LeanGraphService/GetDependentNodesAndEdges',
            state__search_dot_v1_dot_state__search__pb2.GetDependentNodesAndEdgesRequest.SerializeToString,
            state__search_dot_v1_dot_state__search__pb2.GetDependentNodesAndEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
