# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state_search/v1/state_search.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'state_search/v1/state_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"state_search/v1/state_search.proto\x12\x0fstate_search.v1B\x80\x01\n\x13\x63om.state_search.v1B\x10StateSearchProtoP\x01\xa2\x02\x03SXX\xaa\x02\x0eStateSearch.V1\xca\x02\x0eStateSearch\\V1\xe2\x02\x1aStateSearch\\V1\\GPBMetadata\xea\x02\x0fStateSearch::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_search.v1.state_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.state_search.v1B\020StateSearchProtoP\001\242\002\003SXX\252\002\016StateSearch.V1\312\002\016StateSearch\\V1\342\002\032StateSearch\\V1\\GPBMetadata\352\002\017StateSearch::V1'
# @@protoc_insertion_point(module_scope)
